Add HTML skeleton and implement flexbox
AlexHamn/portfolio pull request #1
Opened 2021-07-09 04:18 UTC by AlexHamn

The HTML skeleton for the headline section is complete.
Created a CSS file with full implementation of flexbox.
The styling for all text is correctly configured.

2021-07-09 05:31 UTC, bellom requested changes
## Hi @AlexHamn  👏 , 

### Awesome job so far!! :+1: 

#### You have done wonderfully well setting up linter and good commit messages 🔥, However, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Required Changes! ♻️ 

1. Kindly check the comments under the review.

2. Great simple design 👍  but we need to stick to Microverse curriculum plan. so that we can build the skills needed to land a job.
![image](https://user-images.githubusercontent.com/31897434/125027804-c75a0a00-e07e-11eb-86ce-ec1b956d8c57.png)

let's take one step back, kindly go to the [Project Requirement Page](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) under Project requirements.
_You must stick to the design as much as possible (e.g. font, colors, images, tests, margins) using the templates in this [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)._


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 05:31 UTC, bellom commented on README.md
> +
Good job setting up this README file.
If check the [Microverse template](https://github.com/microverseinc/readme-template) you will see there is a section where you're supposed to add `Setup`.

kindly add the following;
- screenshot from your app.
- live demo link
- setup

Example of a good setup that helps the non-technical user to set up your app easily below;
```
Example: 
- git clone `your repo`
- cd into the folder
- git checkout `branch-name`
- open `index.html` with live server
```

2021-07-09 05:31 UTC, bellom commented on index.html
> +      <p>Alex Hamn</p>
Following the [Semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp).
 `Your name` should be wrap in an `h1` tag which is the main title of the page so it is good practice to use `h1` tag.

2021-07-09 18:11 UTC, AlexHamn commented
Would you mind telling me how to interpret the linter errors? 🙏🏼 
Cause I don't have the first clue about what all the error messages are trying to say.

2021-07-09 21:01 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️ 


## Hello @AlexHamn ✋🏼  Nice done with working on last review.However there are still some issues you should fix. Please fix them then your project will be approved.





### ♻️ Request changes ♻️
 
- [ ] You should follow the design.

_**Check the comment about that  under the review.**_








### OPTIONAL SUGGESTIONS

#### These are optional 

### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/LmNwrBhejkK9EFP504/giphy.gif)
___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-09 21:01 UTC, ahmetbozaci commented on index.html
> +    <main>
**Mandatory** 
- [ ] Like last TSE review you should follow original design. You can use background image for that.

**OPTIONAL**
- [ ] Also your navigation bar has line original page has not. You can fix this too.


**Yours:**
![image](https://user-images.githubusercontent.com/38635158/125134469-1734e180-e110-11eb-9c41-6e26e98822cd.png)
___
**Original:**
![image](https://user-images.githubusercontent.com/38635158/125134490-1d2ac280-e110-11eb-8299-b633c9518a4e.png)

2021-07-09 22:33 UTC, AlexHamn commented on index.html
> +    <main>
Hi Ahmet, thank you for your help. That is very strange; the code for the background images is in the CSS file, and also, in my browser, I don't see any line at the top of the page; you can see it in the attached screenshot. Would you mind explaining to me why this happens or how could I fix it? 🙏🏼 

![ksnip_20210709-172818](https://user-images.githubusercontent.com/81324033/125141815-ad024980-e0db-11eb-98e9-48f75e87f561.png)

2021-07-10 03:01 UTC, od-c0d3r approved these changes
Hi @AlexHamn , 👋🏼 ^^!

# Approved 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional Changes

_Kindly check the inline comments 👍🏼_ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-10 03:01 UTC, o-rashad commented on README.md
> +
Thank you @AlexHamn for implementing the required changes ^^!

2021-07-10 03:01 UTC, o-rashad commented on index.html
> +    <main>
Good work @AlexHamn the design looks good to me. 💯

2021-07-10 03:01 UTC, od-c0d3r commented on index.html
> +      <h1 class="logo">Alex Hamn</h1>
- [ ] [OPTIONAL] Would it be nice if we made the logo linked to your home page? 🤔 

Try to implement that using an `<a>` tag 👍🏼 

That would enhance your UX. 💹👥

2021-07-10 03:08 UTC, merged